# Generated by Django 3.2 on 2021-04-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20210426_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('n', 'North'), ('s', 'South'), ('e', 'East'), ('w', 'West')], default='n', max_length=1)),
            ],
        ),
    ]
