# Generated by Django 3.2 on 2021-04-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_direction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direction',
        ),
    ]
